.devops/pagopa-deploy-pipelines.yml, README.md, helm/values-dev.yaml, helm/values-prod.yaml
- Upgrated helm dev environment
- Created helm prod environemtn
- added Readme docs for deployment
=> Deploy-helm

web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/subscriptions/Subscription.java
chenged label apykeys
expected)
=> fix label apy keys

app/src/main/resources/swagger/api-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/client/ApiConfigRestClient.java, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationApiConfigHeaderInterceptor.java, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationApiConfigSelfcareIntegrationHeaderInterceptor.java, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationHeaderInterceptor.java, connector/rest/src/test/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationApiConfigHeaderInterceptorTest.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/config/SecurityConfig.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/ChannelController.java, web/src/test/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/ChannelControllerTest.java
add 2 api path to the whitelist
add 2 api path to the whitelist and fix feign interceptor
expected)
=> wip whitelist

app/src/main/resources/swagger/api-docs.json, connector-api/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/api/ExternalApiConnector.java, connector-api/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/model/delegation/Delegation.java, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/client/ExternalApiRestClient.java, connector/rest/src/main/resources/config/external-api-rest-client.properties, connector/rest/src/test/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/client/ExternalApiRestClientTest.java, connector/rest/src/test/resources/stubs/external/mappings/getBrokerDelegation_fullyValued.json, core/src/main/java/it/pagopa/selfcare/pagopa/backoffice/core/ExternalApiService.java, core/src/main/java/it/pagopa/selfcare/pagopa/backoffice/core/ExternalApiServiceImpl.java, core/src/test/java/it/pagopa/selfcare/pagopa/backoffice/core/ExternalApiServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/InstitutionController.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/delegation/DelegationResource.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/mapper/DelegationMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/InstitutionControllerTest.java
implementation new api
implementation new api about delega
expected)
=> wip delegation psp ec

app/src/main/resources/swagger/api-docs.json, openapi/openapi.json, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/creditorInstituions/CreditorInstitutionStationDto.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/mapper/CreditorInstitutionMapperImpl.java
add fields into CI dto
update api-docs
update openapi.json
add fields into CI dto
update api-docs
update openapi.json
expected)
=> add fields on CI dto

web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/ChannelController.java
fix get all channel merged whit brokerCode
expected)
=> fix get all channel merged whit brokerCode

web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/security/JwtAuthenticationStrategyFactoryImpl.java
fixed jwt startegy prod string iss
fixed jwt startegy prod string iss
expected)
=> fixed jwt strategy prod string iss

helm/values-prod.yaml
=> Update Cors from helm prod configuration

helm/values-prod.yaml
fix JWT_TOKEN_PUBLIC_KEY_PROD
fix JWT_TOKEN_PUBLIC_KEY_PROD
expected)
=> fix JWT_TOKEN_PUBLIC_KEY_PROD

app/src/main/resources/swagger/api-docs.json, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/creditorinstituions/CreditorInstitutionAddressResource.java
remove required field taxDomicile
expected)
=> remove required field

connector-api/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/api/TavoloOpConnector.java, connector/dao/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/dao/TavoloOpConnectorImpl.java, connector/dao/src/test/java/it/pagopa/selfcare/pagopa/backoffice/connector/dao/TavoloOpConnectorImplTest.java, core/src/main/java/it/pagopa/selfcare/pagopa/backoffice/core/TavoloOpService.java, core/src/main/java/it/pagopa/selfcare/pagopa/backoffice/core/TavoloOpServiceImpl.java, core/src/test/java/it/pagopa/selfcare/pagopa/backoffice/core/TavoloOpServiceImplTest.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/TavoloOpController.java, web/src/main/java/it/pagopa/selfcare/pagopa/backoffice/web/model/mapper/TavoloOpMapper.java, web/src/main/resources/swagger/swagger_en.properties, web/src/test/java/it/pagopa/selfcare/pagopa/backoffice/web/controller/TavoloOpControllerTest.java
wip update tavolo operativo
wip update tavolo operativo
expected)
=> wip update tavolo operativo

connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationApiConfigHeaderInterceptor.java
check if param code is empty
if code is empty skip check 
expected)
=> check if param code is empty

app/src/main/resources/swagger/api-docs.json, connector/rest/src/main/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/interceptor/AuthorizationApiConfigHeaderInterceptor.java, connector/rest/src/test/java/it/pagopa/selfcare/pagopa/backoffice/connector/rest/client/ApiConfigRestClientTest.java, connector/rest/src/test/resources/stubs/channels/mappings/getStations_fullyValued.json, helm/values-dev.yaml
correct PARAMS_NAME, active authorization in DEV
correct PARAMS_NAME, active authorization in DEV
expected)
=> correct PARAMS_NAME, active authorization in DEV

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtil.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/util/LegacyPspCodeUtilTest.java, src/test/resources/response/externalapi/institution_response.json
- Introduced filter to fix delegates recovery based from allowed institution types mapped for roles
- Removed limit on pspCode
https://pagopa.atlassian.net/browse/VAS-709
expected)
=> [VAS-709] fix: update delegation with role filter

Dockerfile, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/LoggingAspect.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
- 🔨 fix null pointer
- 🖊️ code refactoring
expected)
=> Hotfix: getDelegation

.github/workflows/create_dashboard.yml, .opex/backoffice/env/prod/backend.ini, .opex/backoffice/env/prod/backend.tfvars, .opex/backoffice/env/prod/config.yaml, .opex/backoffice/env/prod/terraform.tfvars, .opex/backoffice/env/uat/backend.ini, .opex/backoffice/env/uat/backend.tfvars, .opex/backoffice/env/uat/config.yaml, .opex/backoffice/env/uat/terraform.tfvars
- added GHA to create opex dashboard
- add opex config files
expected)
=> [VAS-710] feat: Add opex dashboard GHA

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/RoleType.java, src/test/resources/application.properties
- handled null values for the roletype enumeration
- handled others selfcare roles
bug fixing
manually
expected)
=> bug fixing: RoleType

.opex/backoffice/env/prod/backend.tfvars, .opex/backoffice/env/uat/backend.tfvars
=> new terraform state

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
- Changed getBrokerAndPspDetails API's signature from pspCode to taxCode
- Implemented pspCode recovery from taxCode
- Updated unit test
- Updated openapi specs
[VAS-693](https://pagopa.atlassian.net/browse/VAS-693?atlOrigin=eyJpIjoiMGUzNzE3ZWFjM2ExNGQwMTlkOTBmZWMxODhkNDdlNDEiLCJwIjoiaiJ9)
expected)
[VAS-693]: https://pagopa.atlassian.net/browse/VAS-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-693] feat: Changed getBrokerAndPspDetails API

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
=> [VAS-694] feat: Update PUT PSP API to use psp tax code

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
- Changed getFirstValidChannelCode API input from pspCode to taxCode
[VAS-695](https://pagopa.atlassian.net/browse/VAS-695?atlOrigin=eyJpIjoiNWZjOTJmMzUzMzVhNGQzMzg5Yjg3ZjVhZWNkNWVkODMiLCJwIjoiaiJ9)
expected)
[VAS-695]: https://pagopa.atlassian.net/browse/VAS-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-695] Changed getFirstValidChannelCode API path param

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelPspResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelPsp.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java
- updated `disassociatePSPFromChannel` API to use PSP tax code
- updated `getChannelPaymentServiceProviders` API response with PSP tax code
- updated unit test
expected)
=> [VAS-696] feat: Disassociate PSP from channel with fiscal code

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/taxonomies/TaxonomyGroup.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/taxonomies/TaxonomyGroupArea.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/taxonomies/TaxonomyGroups.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyServiceTest.java
- Introducing API to recover taxonomy groups
https://pagopa.atlassian.net/browse/VAS-798
expected)
=> [VAS-798] feat: add taxonomy group api

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/TaxonomyEntity.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/TaxonomyControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyServiceTest.java
- Updated taxonomies API to retrieve data from the Mongo DB instance
https://pagopa.atlassian.net/browse/VAS-779
expected)
=> [VAS-779] feat: add taxonomy api

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
- updated subscription for backoffice external
- updated unit test
expected)
=> [VAS-853] feat: Handle backoffice external new product

openapi/openapi.json
- Introducing updated openapi
expected)
=> fix openapi

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java, src/test/resources/application.properties, src/test/resources/bootstrap.properties
- Updated channel available-code API to recover channel data based on the taxCode as brokerCode
- Removed unnecessary conversion to pspCode, and related references
https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-860
expected)
=> [VAS-862] fix: Updated available-code service to use brokerCode

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/IbanController.java
- Fixed createIban openapi response specs
When sending response to front-end, the call was deemed invalid and rejected
expected)
=> fix: Fixed createIban openapi response

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertDelegationExternalToMyCIResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationPage.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/MyCIResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
- added new api to retrieve creditor institution's broker delegations
- added unit test
Add new page "I miei enti"
expected)
=> [VAS-689] feat: Add ci broker delegation page api

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java
- fix apiconfig selfcare parameter
expected)
=> fix: apiconfig parameter

src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java
- removed caching from getCIBrokerDelegation API
expected)
=> Remove cache from getCIBrokerDelegation API

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
- handled not found on get CI CBILL code
Handled case where the CI is not registered on NODO DEI PAGAMENTI
expected)
=> Add error handling on get cbill api

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/TaxonomyEntity.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertCreditorInstitutionViewToCIBrokerStationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CIPaymentContact.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionContactsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionView.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionsView.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerStationPage.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerStationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionProductUsers.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/tavoloop/TavoloOpResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TavoloOpRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/OperativeTableService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/OperativeTableServiceTest.java
- added new API to retrieve creditor institution's contacts
- added new API to retrieve broker's station associated to a specific creditor institution
expected)
=> [VAS-691] feat: Add delegation details page API

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertDelegationExternalToCIBrokerDelegationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/CIBrokerDelegationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
- added new field `is_institution_signed_in` that describe if an institution i signed in on Nodo dei pagamenti
- do some refactor to improve GET delegation list API performance
expected)
=> [VAS-929] fix: Add new field to delegation list api

pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/repository/TransactionalBulkDAOTest.java, src/test/java/utils/MemoryAppender.java
- upgrade ***Spring Cloud*** version from `2020.0.4` to `2021.0.9` to have Feign client caching support
- upgrade ***Spring Boot*** version from `2.6.1` to `2.7.18` to support new Spring Cloud version
- removed `springdoc-openapi-starter-webmvc-ui` dependency
- removed `de.flapdoodle.embed.mongo` dependency
- added caching on `getBrokerDelegation` Selfcare client API
- fixed unit tests
expected)
=> [VAS-952]  Improve for PROD release

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleFee.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CISubscriptionInfo.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleCISubscriptionsDetail.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleCISubscriptionsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PublicBundleSubscriptionStatus.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreditorInstitutionResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleAttribute.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleDetails.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiFiscalCodeList.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspBundleRequest.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspCiBundleAttribute.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PspRequests.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/TransferCategoryRelation.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/PageInfo.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/CreditorInstitutionInfo.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- added API to retrieve creditor institutions subscribed to a public bundle
- added API to retrieve creditor institutions that have requested a subscription to a public bundle
- added API to retrieve subscriptions details
[Task-799](https://pagopa.atlassian.net/browse/VAS-799)
expected)
=> [VAS-799] feat: Add Retrieve public bundle's subscriptions APIs

docker/run_docker.sh, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GpdClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/TaxonomyClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/ResponseValidator.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionInfoToInstitutionResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/BrokerPspDetailsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProviderDetailsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProviderResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PaymentServiceProvidersResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/PspChannelsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Institution.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionInfo.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PaymentServiceProviderControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/PspBrokerControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
🔎  This PR adds a response validator for us and our dependencies.
expected)
=> response validator

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/PublicBundleRequest.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- updated `POST /payment-service-providers/{psp-tax-code}/requests/{bundle-request-id}/accept` to follow what defined in Figma
- aligned `POST /payment-service-providers/{psp-tax-code}/requests/{bundle-request-id}/reject` with accept API
- updated `PublicBundleRequests` model
expected)
=> [VAS-1005] chore: Update PSP accept public bundle subscription

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
…alid bundles and updated unit tests
- excluded not active public bundles from CI API
expected)
=> [VAS-1007] Retrieve only active public bundles for CI

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- enabled retrieve of payment contacts from Selfcare
- enabled unit tests
expected)
=> [VAS-1006] feat: Enable retrieve of payment contacts

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
- enabled email notification in `DEV`/`UAT` environments to test email (`TEST_EMAIL` environment variable)
- removed unused code
expected)
=> [VAS-1026] feat: Enable email notification in test environment

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java
=> hotfix: required field

README.md, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/MaintenanceController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/MaintenanceEntity.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/maintenance/MaintenanceMessage.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/MaintenanceRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/MaintenanceService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/MaintenanceControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/MaintenanceServiceTest.java
- added new API `GET /maintenance/message`
- fixed readme
[VAS#1036](https://pagopa.atlassian.net/browse/VAS-1036)
expected)
=> [VAS-1036] feat: Add get maintenance message api

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleTaxonomy.java
- removee required from get bundles response
Removed required to allow a "generic" public bundle attribute
expected)
=> [VAS-1031] Remove required from get bundles response

src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/azure/FeatureFilterConfigurations.java
=> timewindow

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/PSPBundleTaxonomy.java
- Add ecType to PSPBundleTaxonomy
Needed for the front end to display
expected)
=> fix: Add ecType to PSPBundleTaxonomy

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java
- added isConnectionSync field to `GET /stations/merged/{station-code}`
Added flag to describe the type of connection for the station
[VAS#1009](https://pagopa.atlassian.net/browse/VAS-1009)
expected)
=> [VAS-1009] feat: Add connection synchronous flag

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/resources/templates/acceptPublicBundleSubscriptionEmail.html, src/main/resources/templates/rejectPublicBundleSubscriptionEmail.html
- removed old bundle naming from email template
[VAS#1044](https://pagopa.atlassian.net/browse/VAS-1044)
expected)
=> [VAS-1044] fix: Remove old bundle naming from email template

.github/workflows/release_deploy.yml
the latest version on github is only the prod release
expected)
=> new inputs for GHA Release and Deploy

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/ConfigurationStatus.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStations.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationCodeResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
- update GET /stations API to return ACTIVE or TO_BE_VALIDATED stations
[VAS#948](https://pagopa.atlassian.net/browse/VAS-948)
expected)
=> [VAS-948] feat: Update get stations API

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigSelfcareIntegrationClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCode.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/CreditorInstitutionAssociatedCodeList.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
=> fix: pre release

src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java
=> [fix-release-2] fix isNotBlank conditions

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/OperatorStationReview.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/main/resources/templates/channelCreationValidatedEmail.html, src/main/resources/templates/channelUpdateValidatedEmail.html, src/main/resources/templates/createBundleSubscriptionRequestEmail.html, src/main/resources/templates/deleteBundleSubscriptionEmail.html, src/main/resources/templates/rejectPublicBundleSubscriptionEmail.html, src/main/resources/templates/stationCreationValidatedEmail.html, src/main/resources/templates/stationReviewRequestedEmail.html, src/main/resources/templates/stationUpdateValidatedEmail.html, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
- updated `PUT /stations/wrapper/{station-code}/operator` API to allow operator to add station review note
- added email notification 
expected)
=> [VAS-822] feat: Add operator station review 

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java
- Added openapi response details to createBundle & updateBundle Apis
- Updated openapi
[VAS-1047](https://pagopa.atlassian.net/browse/VAS-1047?atlOrigin=eyJpIjoiODcyNjc5ZGVlYWI5NGFlMWIzNWQ1MzYwMTIzNDQxY2EiLCJwIjoiaiJ9)
expected)
[VAS-1047]: https://pagopa.atlassian.net/browse/VAS-1047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-1047] feat: Add ApiResponse specifications to create & update bundle

helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/InstitutionsClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/feign/InstitutionsFeignClientConfig.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java, src/main/resources/application.properties, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionsControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsServiceTest.java, src/test/resources/application.properties
- Introducing API to update institutions for notices
- Updated unit testing
expected)
=> [VAS-976] feat: add notice institutions api

infra/04_apim_api.tf, infra/99_locals.tf
changed the infra files
to update the new APIM
expected)
=> update swagger at New APIM [Infra apply]

.github/workflows/ci_integration_test.yml, docker/run_docker.sh, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
🐛 change the boolean to true when PSP use the bundles
- we have to use the `pspCode` with BIC
[Jira task](https://pagopa.atlassian.net/browse/VAS-1071)
expected)
=> [VAS-1071] PSP has to act as direct when use the bundles

.github/workflows/cd_main.yml
=> pre_release

.github/workflows/deploy_with_github_runner.yml
=> hotfix selfhosted runner

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionInfoResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/DelegationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionApiKeysResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetailResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/ProductResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/InstitutionApiKeys.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/InstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/IbanServiceTest.java
- Fixed openapi generation changing the response body from array of elements to an object  for 
- getAvailableCreditorInsitutionsForStation API 
- getInstitutions
- getBrokerDelegation
- getInstitutionProducts
- getInstitutionApiKeys
- createInstitutionApiKeys
[VAS#1074](https://pagopa.atlassian.net/browse/VAS-1074)
The client generation library couldn't generate the right response
expected)
=> fix: Openapi client generation

.github/workflows/cd_main.yml, .github/workflows/cd_next.yml, .github/workflows/release_deploy.yml
- bump maven-release version in github actions from `v1.13.3` to `v1.14.1`
expected)
=> hotfix: Bump maven-release version in github actions

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/notices/InstitutionUploadData.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- added API `/bundles/{id-bundle}/payment-service-providers/{psp-tax-code}/offers/{bundle-offer-id}` to delete private bundle offers
- added unit test
[VAS#944](https://pagopa.atlassian.net/browse/VAS-944)
expected)
=> [VAS-944] feat: Add private bundle delete offer API

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java
- removed useless API call
Fix station validation flow
expected)
=> fix: Station validation flow

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/InstitutionsClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/NoticeController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java
- fixed getInstitutionData model in openapi
expected)
=> fix: updated notices ci client

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleSubscriptionStatus.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/CIBundleResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCIOffers.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleDetails.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundleOffer.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiBundles.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
depends on https://github.com/pagopa/pagopa-selfcare-frontend/pull/540
- updated GET /bundles/creditor-institutions with logic to retrieve CI private bundles
expected)
=> [VAS-959] feat: Add CI private bundle table API

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleOffered.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/CiTaxCodeList.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/creditorinstitution/ApiConfigCreditorInstitutionsOrderBy.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionInfo.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/main/resources/templates/acceptPublicBundleSubscriptionEmail.html, src/main/resources/templates/createBundleSubscriptionOfferEmail.html, src/main/resources/templates/rejectPublicBundleSubscriptionEmail.html, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- added new `POST /bundles/{id-bundle}/payment-service-providers/{psp-tax-code}/offers` to create private bundle offers
- improved `GET /creditor-institutions`
expected)
=> [VAS-940] feat: Add create private bundle offers API

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, infra/04_apim_api.tf, openapi/openapi.json, pom.xml
=> fix: Deploy

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/resources/templates/deleteBundleSubscriptionOfferEmail.html, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- added CI mail notification on private bundle offer delete by the PSP
- updated unit test
expected)
=> [VAS-1085] feat: Add mail notification on bundle offer delete

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/resources/application.properties
set timeout to 200000 ms
expected)
=> Feign Timeout

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/BundleResource.java
- Added new field pspBusinessName to BundleResource class
- Update openapi
[VAS-1103](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-1103)
expected)
[VAS-1103]: https://pagopa.atlassian.net/browse/VAS-1103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-1103] feat: Add new field pspBusinessName to bundle details

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/TaxonomiesExtractionScheduler.java
- Added new config to generate new api key for printPaymentsNotice product
[VAS-1133](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-1133)
expected)
[VAS-1133]: https://pagopa.atlassian.net/browse/VAS-1133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-1133] feat: Add new api key for printPaymentsNotice product

src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityChannel.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityChannels.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/WrapperChannelList.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperChannelsRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
- avoid the raw usage of generics in channels api
expected)
=> [VAS-1149] fix: Wrapper channel raw generic

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperStationsRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/AllPages.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionSchedulerTest.java
- fixed cast exception
expected)
=> [VAS-1151] hotfix: cast exception during export job

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
- Implemented authorizer to verify user when creating a new api key for GPD service
- Refactored and improved code
[VAS-962](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-962)
expected)
[VAS-962]: https://pagopa.atlassian.net/browse/VAS-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-962] feat: Implement authorizer when creating GPD key

CODEOWNERS, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/CreditorInstitutionIbansEntity.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/IbanEntity.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/CreditorInstitutionsIbansRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TransactionalBulkDAO.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/repository/TransactionalBulkDAOTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionSchedulerTest.java
➕ Added a new collection `creditorInstitutionIbans` 
✏️ Edited the cron job to save the ibans in the new collection
Extra
🛡️ **CODEOWNERS** file edited: added `pagopa-core-team`
[Jira Ticket ](https://pagopa.atlassian.net/browse/VAS-1195)
✋ Manually
expected)
=> [VAS-1195] New CI IBANs Mongo Collection

CODEOWNERS, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitution.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/users/client/UserInstitutionProduct.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- Reworked api to retrieve institutions, defined using userInstitutions api and removing usage of deprecated api
- Updated unit test
- introduced cache for institutions retrieval api
expected)
=> [VAS-1168] feat: rework get institutions

helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
🧰  fix cache in `getInstitutions` method
expected)
=> hotfix getusers

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/commissionbundle/client/BundleCreateResponse.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
📦 when a bundle GEC is create a new Jira ticket is onped in SMO board
To monitoring the bundles
expected)
=> [VAS-1203] open ticket when a bundle is created

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ExternalApiClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- rollback for getInstitutions (branching from main)
expected)
=> feat: rollback on getInstitutions service

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/creditorinstituions/CreditorInstitutionStationEditResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CreditorInstitutionControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- Defined new API to update the CI-station relationship
- Updated classes to handle new flags `standIn` & `aca`
- Updated openapi
[VAS-981](https://pagopa.atlassian.net/jira/software/c/projects/VAS/boards/540?selectedIssue=VAS-981)
Unit tests
expected)
[VAS-981]: https://pagopa.atlassian.net/browse/VAS-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [VAS-981] feat: Introduce new flags "standIn" & "aca" for CI-station relation

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
🐛 hotfix to trigger the authorizer configuration when a GPD key is regenerated
➖  missing feature
✋ manually
🤖 Junit
expected)
=> [PAGOPA-1992] regenerate key

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/CreateStationMaintenance.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/OffsetDateTimeDeserializer.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationMaintenanceControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceServiceTest.java
depends on https://github.com/pagopa/pagopa-api-config/pull/309
- Implemented proxy to api-config's API createStationMaintenance
- Defined utility and request/response classes
- Defined new unit tests
- Updated openapi
[PPANTT-47](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-47)
Unit test
expected)
[PPANTT-47]: https://pagopa.atlassian.net/browse/PPANTT-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-47] feat: API create stations' maintenance

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/PspData.java
=> Hotfix legal number

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java
=> fix: Path api-config api station maintenance

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/CreateStationMaintenance.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/StationMaintenanceResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stationmaintenance/UpdateStationMaintenance.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationMaintenanceService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java
- improve date format in station maintenance models
expected)
=> fix: Date format

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
- added fallback in edit mode to retrieve station or channel details that are not present in wrapper storage
[PPANTT-86](https://pagopa.atlassian.net/browse/PPANTT-86)
expected)
[PPANTT-86]: https://pagopa.atlassian.net/browse/PPANTT-86?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix: Station/Channel not in wrapper

src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/authorization/AuthorizationOwner.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/PspData.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
=> chore: Merge main

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
- Added new api key for ACA's service (PPANTT-93)
- Refactored methods
- Added auth domain to GPD_PAY & GPD_REP (PPANTT-92)
[PPANTT-92](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-92)
[PPANTT-93](https://pagopa.atlassian.net/browse/PPANTT-93)
expected)
[PPANTT-92]: https://pagopa.atlassian.net/browse/PPANTT-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPANTT-92]: https://pagopa.atlassian.net/browse/PPANTT-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PPANTT-93]: https://pagopa.atlassian.net/browse/PPANTT-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-93] feat: Add api key ACA

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java
- Changed empty string to null in products subscription config
Readability and usage
expected)
=> fix: Change empty string to null in products subscription config

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/GecClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- Modified PSP's Bundles' list API
- Added new param to order bundles by maxPaymentAmount
- Added new params to filter bundles by paymentAmount
- Added new params to filter bundles by validity dates
[PPANTT-99](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-99)
[PPANTT-99]: https://pagopa.atlassian.net/browse/PPANTT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-99] feat: New filters PSP bundles' list

src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java, src/main/resources/templates/expiringBundleEmail.html, src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java
- fixed notification on bundle delete
- fixed notification cron for expiring bundle
- added PSP name and tax code info in expiring bundle mail
- fixed mail template
Correctly notify all EC on bundle delete and add new info in expiring bundle mail
expected)
=> fix: Commission bundle mail notification

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPages.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/function/BundleAllPagesTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ExportServiceTest.java
- added API to export all bundle of a PSP in CSV format
[PPANTT-101](https://pagopa.atlassian.net/browse/PPANTT-101)
expected)
[PPANTT-101]: https://pagopa.atlassian.net/browse/PPANTT-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-101] feat: Add export PSP bundle api

src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/Subscription.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
- Added delegations to authorized entities for GPD & ACA products
- Changed primary/secondary key regeneration to retrieve again the institution's delegations
- Refactored code
[PPANTT-104](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-104)
expected)
[PPANTT-104]: https://pagopa.atlassian.net/browse/PPANTT-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-104] fix: Add delegations to authorizer for all GPD & ACA products

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClient.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClientTest.java
- added check on current enviroment before JIRA ticket creation
[PPANTT#103](https://pagopa.atlassian.net/browse/PPANTT-103)
expected)
=> [PPANTT-103] chore: Avoid jira ticket creation below uat env

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClient.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/JiraServiceManagerClientTest.java
- fixed environment checks to upper case
expected)
=> hotfix: Checks on environment

src/main/java/it/pagopa/selfcare/pagopa/backoffice/entity/WrapperEntityChannels.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
- added create wrapper fallback when updating a legacy station or channel aka station or channel saved only on ApiConfig
[PPANTT-110](https://pagopa.atlassian.net/browse/PPANTT-110)
expected)
[PPANTT-110]: https://pagopa.atlassian.net/browse/PPANTT-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix: [PPANTT-110] Handle legacy station and channel update

src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/Station.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/Stations.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/WrapperChannelsRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/StringUtils.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/PaymentServiceProviderServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
- fixed channel and station code generation for PT
[PPANTT-113](https://pagopa.atlassian.net/browse/PPANTT-113)
expected)
[PPANTT-113]: https://pagopa.atlassian.net/browse/PPANTT-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hotfix: [PPANTT-113] Station and Channel code generation

src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/StationDetails.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java
- Added new fields to Station's models for REST endpoint and flag payment options
[PPANTT-72](https://pagopa.atlassian.net/jira/software/c/projects/PPANTT/boards/617?selectedIssue=PPANTT-72)
expected)
[PPANTT-72]: https://pagopa.atlassian.net/browse/PPANTT-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-72] feat: Add new fields to Station's models for REST endpoint and flag payment options

openapi/openapi.json
=> updated openapi

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ChannelMapper.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/StationMapperImpl.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/ChannelDetailsResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/channels/WrapperChannelResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/channel/ChannelDetails.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/station/StationDetails.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperChannel.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/connector/wrapper/WrapperStation.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/StationDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationDetailsDto.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/stations/WrapperStationResource.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java
- Updated flag standIn properties to channel and stations
- Updated mappers
- updated next with hotfix
[PPANTT-138](https://pagopa.atlassian.net/browse/PPANTT-138)
expected)
[PPANTT-138]: https://pagopa.atlassian.net/browse/PPANTT-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-138] feat: add standin flag

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
=> [PPANTT-153] fix: Error handling in dissociate CI station

src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java
- Updated query to check taxonomies based on updated values
expected)
=> [PPANTT-151] feat: Reworked taxonomy query

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AuthorizerConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/repository/TaxonomyRepository.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/TaxonomyService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/CreditorInstitutionServiceTest.java
- Updated taxonomy recovery with regex match
expected)
=> Ppantt 151 rework taxonomy query

src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/MappingsConfiguration.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertInstitutionToInstitutionBase.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/mapper/ConvertUserInstitutionToInstitutionBase.java
- Fixed the mapping between Institution and InstitutionBase
expected)
=> fix: Conversion Institution to InstitutionBase for pagopaOperator

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java
- fixed retrieve of field `activationDate`
expected)
=> fix: Activation date

src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CiBrokerExtractionScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/IbanByBrokerExtractionScheduler.java
- call MDC clear only on exception
Avoid MDC clear on success api call
expected)
=> fix: Cron logs metadata

.github/workflows/deploy_with_github_runner.yml
- updated deploy gha with self host job
[PPANTT-218](https://pagopa.atlassian.net/browse/PPANTT-218)
expected)
[PPANTT-218]: https://pagopa.atlassian.net/browse/PPANTT-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-218] fix: Deploy gha

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AsyncNotificationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ChannelService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/CommissionBundleService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/MailTextConstants.java, src/main/resources/templates/acceptBundleSubscriptionOfferEmail.html, src/main/resources/templates/acceptBundleSubscriptionRequestEmail.html, src/main/resources/templates/channelReviewRequestedEmail.html, src/main/resources/templates/createBundleSubscriptionOfferEmail.html, src/main/resources/templates/createBundleSubscriptionRequestEmail.html, src/main/resources/templates/deleteBundleEmail.html, src/main/resources/templates/expiringBundleEmail.html, src/main/resources/templates/stationReviewRequestedEmail.html, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsSesClientTest.java
- parametrized url in mail content to reflect the source environment
- added environment in mail subject (only for test environment)
[PPANTT-215](https://pagopa.atlassian.net/browse/PPANTT-215)
expected)
[PPANTT-215]: https://pagopa.atlassian.net/browse/PPANTT-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-215] feat: Add environment info in mail content

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/ApiManagementServiceTest.java
- reintroduced authorized entities configuration for BO External API key with owner info
[PPANTT-222](https://pagopa.atlassian.net/browse/PPANTT-222)
expected)
[PPANTT-222]: https://pagopa.atlassian.net/browse/PPANTT-222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PPANTT-222] fix: BO external authorizer config

docker/run_docker.sh, helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml
=> chore(pom): new versions

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/StationService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/StationControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/StationServiceTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/WrapperServiceTest.java
=> fix: PIDM-153 Resolve Update Station StackOverflow bug

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/component/ApiManagementComponent.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/SelfCareUser.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/InstitutionDetail.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/model/institutions/client/Onboarding.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/security/PagopaAuthenticationStrategy.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Constants.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/util/Utility.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
[PIDM-87](https://pagopa.atlassian.net/browse/PIDM-87)
expected)
[PIDM-87]: https://pagopa.atlassian.net/browse/PIDM-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [PIDM-87] Improvements quicksight dashboard

src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/client/AwsQuicksightClientTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
- Added pspName parameter to quicksight dashboard url
- Updated unit test
The pspName is needed in the quicksight dashboard
expected)
=> feat: Added pspName parameter to quicksight dashboard url

helm/Chart.yaml, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, openapi/openapi.json, pom.xml, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/InstitutionsServiceTest.java
The API POST /institutions/data will now propagate a 400 http code of printit dependency instead of converting it to 500
expected)
=> [PIDM-45] chore(exception): propagate printit downstream dependency's 400

src/main/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationScheduler.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/scheduler/CommissionBundleMailNotificationSchedulerTest.java
Changed SMO notification mechanism , from mail to Jira task
it'll overcame operations@pagopa.it mail address dismission and reorganize SMO notification process
expected)
=> [PIDM-291] fix: SMO notification change

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/exception/AppError.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/AwsQuicksightControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightServiceTest.java
- added `institutionId` query param to `/quicksight/dashboard` API
- updated logic to use the `institutionId` provided via query param if the user is a pagoPA operator
- updated tests
[PIDM-370](https://pagopa.atlassian.net/browse/PIDM-370)
expected)
[PIDM-370]: https://pagopa.atlassian.net/browse/PIDM-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PIDM-370] fix: PSP dashboard for operator

src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/AwsQuicksightService.java
- added `isOperator` flag to MDC properties
Allow to better Quicksight dashboard activity tracing
expected)
=> chore: Improve Quicksight dashboard log

src/main/java/it/pagopa/selfcare/pagopa/backoffice/config/JwtAspect.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/CommissionBundleController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/security/JwtSecurity.java
- Added Broken Access Control check on the following API:
- `GET /bundles/creditor-institutions`
- `POST /bundles/creditor-institutions/{ci-tax-code}/offers/{id-bundle-offer}/accept`
- `POST /bundles/creditor-institutions/{ci-tax-code}/offers/{id-bundle-offer}/reject`
- `POST /bundles/creditor-institutions/{ci-tax-code}/requests`
- `DELETE /bundles/creditor-institutions/{ci-tax-code}/requests/{bundle-request-id}`
- `GET /bundles/payment-service-providers/{psp-tax-code}`
- `POST /bundles/payment-service-providers/{psp-tax-code}`
- `GET /bundles/payment-service-providers/{psp-tax-code}/export`
- `POST /bundles/payment-service-providers/{psp-tax-code}/requests/{bundle-request-id}/accept`
- `POST /bundles/payment-service-providers/{psp-tax-code}/requests/{bundle-request-id}/reject`
- `DELETE …
=> [PIDM-441] chore: VA-PT Step 2

openapi/openapi.json, src/main/java/it/pagopa/selfcare/pagopa/backoffice/client/ApiConfigClient.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerController.java, src/main/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerService.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/controller/BrokerControllerTest.java, src/test/java/it/pagopa/selfcare/pagopa/backoffice/service/BrokerServiceTest.java
Deleted the following APIs:
- `getBrokersEC                             GET /brokers`
- `updateBroker                             PUT /brokers/{broker-tax-code}`
- `getStationsDetailsListByBroker           GET /brokers/{broker-tax-code}/stations`
The APIs were not utilized, deleted to prevent improper external use
expected)
=> chore: Delete unused BrokerController apis

.github/workflows/deploy_with_github_runner.yml
- Introduced a `set -euo pipefail` directive to improve script safety.
- Quoted the `environment` input variable and stored it in `ENVIRONMENT` for better readability and to prevent shell injection.
- Replaced direct use of `${{ inputs.environment }}` in shell commands with the safe `ENVIRONMENT` variable.
This change mitigates a potential **shell injection vulnerability** 
- Manually tested the updated GitHub Actions workflow in a feature branch across `dev` env
expected)
The error present in deploy also appears on main and is not related to the pr.
=> fix: [CHK-4139] GitHub run shell injection
